FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONPATH=/home/ubuntu/llm_gateway/src

ARG UID
ARG GID

RUN apt update && \
    apt install -y wget git build-essential python3 libpython3-dev python3-venv curl neovim cmake ninja-build && \
    groupadd -g $GID ubuntu && useradd -m -u $UID -g $GID ubuntu -s /usr/bin/bash

COPY requirements.lock /tmp/requirements.lock

RUN sed -i '/^-e/d' /tmp/requirements.lock && \
    sed -i -E 's/\+cu[0-9]{3}//g' /tmp/requirements.lock && \
    sed -i '/^nvidia/d' /tmp/requirements.lock && \
    python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir -r /tmp/requirements.lock --extra-index-url https://download.pytorch.org/whl/cpu

USER ubuntu

COPY --link --chown=ubuntu:ubuntu . /home/ubuntu/llm_gateway

RUN mkdir -p /home/ubuntu/.cache/llm_gateway

WORKDIR /home/ubuntu/llm_gateway

SHELL ["/bin/bash", "-c"]

ENTRYPOINT ["/home/ubuntu/llm_gateway/docker/entrypoint-cpu.sh"]
