FROM nvidia/cuda:11.8.0-devel-ubuntu22.04 AS build

ENV DEBIAN_FRONTEND=noninteractive
ENV CMAKE_ARGS=-DLLAMA_CUDA=on
ENV CUDA_DOCKER_ARCH=all

RUN apt update && apt install -y wget git build-essential python3 libpython3-dev python3-venv curl neovim cmake ninja-build

COPY requirements.lock /tmp/requirements.lock

RUN sed -i '/^-e/d' /tmp/requirements.lock && \
    python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir -r /tmp/requirements.lock --extra-index-url https://download.pytorch.org/whl/cu118

FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04

RUN apt update && apt install -y wget git build-essential python3 libpython3-dev python3-venv curl neovim

# cat /proc/driver/nvidia/version
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb && \
    dpkg -i cuda-keyring_1.1-1_all.deb && \
    apt update && \
    apt install -y libnvidia-compute-545

ENV PYTHONPATH=/llm_gateway/src

COPY --from=build /opt/venv /opt/venv

COPY --link . /llm_gateway

WORKDIR /llm_gateway

SHELL ["/bin/bash", "-c"]

ENTRYPOINT "/llm_gateway/docker/entrypoint-gpu.sh"
