# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
# AUTO-GENERATED by types_gen.py — do not edit manually

import time
from typing import Any, ClassVar, Literal, TypeAlias
from pydantic import BaseModel, ConfigDict, Field
from llm_gateway.types.chat_utils import make_tool_call_id
from llm_gateway.types.utils import random_uuid


class OpenAIBaseModel(BaseModel):
    model_config = ConfigDict(extra='allow')
    field_names: ClassVar[set[str] | None] = None

class ErrorInfo(OpenAIBaseModel):
    message: str
    type: str
    param: str | None = None
    code: int

class ErrorResponse(OpenAIBaseModel):
    error: ErrorInfo

class ModelPermission(OpenAIBaseModel):
    id: str = Field(default_factory=lambda: f'modelperm-{random_uuid()}')
    object: str = 'model_permission'
    created: int = Field(default_factory=lambda: int(time.time()))
    allow_create_engine: bool = False
    allow_sampling: bool = True
    allow_logprobs: bool = True
    allow_search_indices: bool = False
    allow_view: bool = True
    allow_fine_tuning: bool = False
    organization: str = '*'
    group: str | None = None
    is_blocking: bool = False

class ModelCard(OpenAIBaseModel):
    id: str
    object: str = 'model'
    created: int = Field(default_factory=lambda: int(time.time()))
    owned_by: str = 'vllm'
    root: str | None = None
    parent: str | None = None
    max_model_len: int | None = None
    permission: list[ModelPermission] = Field(default_factory=list)

class ModelList(OpenAIBaseModel):
    object: str = 'list'
    data: list[ModelCard] = Field(default_factory=list)

class PromptTokenUsageInfo(OpenAIBaseModel):
    cached_tokens: int | None = None

class UsageInfo(OpenAIBaseModel):
    prompt_tokens: int = 0
    total_tokens: int = 0
    completion_tokens: int | None = 0
    prompt_tokens_details: PromptTokenUsageInfo | None = None

class RequestResponseMetadata(BaseModel):
    request_id: str
    final_usage_info: UsageInfo | None = None

class JsonSchemaResponseFormat(OpenAIBaseModel):
    name: str
    description: str | None = None
    json_schema: dict[str, Any] | None = Field(default=None, alias='schema')
    strict: bool | None = None

class LegacyStructuralTag(OpenAIBaseModel):
    begin: str
    structural_tag_schema: dict[str, Any] | None = Field(default=None, alias='schema')
    end: str

class LegacyStructuralTagResponseFormat(OpenAIBaseModel):
    type: Literal['structural_tag']
    structures: list[LegacyStructuralTag]
    triggers: list[str]

class StructuralTagResponseFormat(OpenAIBaseModel):
    type: Literal['structural_tag']
    format: Any
AnyStructuralTagResponseFormat: TypeAlias = LegacyStructuralTagResponseFormat | StructuralTagResponseFormat

class ResponseFormat(OpenAIBaseModel):
    type: Literal['text', 'json_object', 'json_schema']
    json_schema: JsonSchemaResponseFormat | None = None
AnyResponseFormat: TypeAlias = ResponseFormat | StructuralTagResponseFormat | LegacyStructuralTagResponseFormat

class StreamOptions(OpenAIBaseModel):
    include_usage: bool | None = False
    continuous_usage_stats: bool | None = False

class FunctionDefinition(OpenAIBaseModel):
    name: str
    description: str | None = None
    parameters: dict[str, Any] | None = None

class LogitsProcessorConstructor(BaseModel):
    qualname: str
    args: list[Any] | None = None
    kwargs: dict[str, Any] | None = None
    model_config = ConfigDict(extra='forbid')
LogitsProcessors = list[str | LogitsProcessorConstructor]

class FunctionCall(OpenAIBaseModel):
    id: str | None = Field(default=None, exclude=True)
    name: str
    arguments: str

class ToolCall(OpenAIBaseModel):
    id: str = Field(default_factory=make_tool_call_id)
    type: Literal['function'] = 'function'
    function: FunctionCall

class DeltaFunctionCall(BaseModel):
    name: str | None = None
    arguments: str | None = None

class DeltaToolCall(OpenAIBaseModel):
    id: str | None = None
    type: Literal['function'] | None = None
    index: int
    function: DeltaFunctionCall | None = None

class ExtractedToolCallInformation(BaseModel):
    tools_called: bool
    tool_calls: list[ToolCall]
    content: str | None = None

class DeltaMessage(OpenAIBaseModel):
    role: str | None = None
    content: str | None = None
    reasoning: str | None = None
    tool_calls: list[DeltaToolCall] = Field(default_factory=list)

class GenerationError(Exception):
    """raised when finish_reason indicates internal server error (500)"""
