# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
# AUTO-GENERATED by types_gen.py — do not edit manually

import time
from typing import Annotated, Any, ClassVar, Literal
from openai.types.chat.chat_completion_audio import ChatCompletionAudio as OpenAIChatCompletionAudio
from openai.types.chat.chat_completion_message import Annotation as OpenAIAnnotation
from pydantic import Field
from llm_gateway.types.chat_utils import ChatCompletionMessageParam
from llm_gateway.types.openai.engine.protocol import AnyResponseFormat, DeltaMessage, FunctionCall, FunctionDefinition, OpenAIBaseModel, StreamOptions, ToolCall, UsageInfo
from llm_gateway.types.logprobs import Logprob
from llm_gateway.types.utils import random_uuid

type BeamSearchParams = Any

type ChatParams = Any

type ModelConfig = Any

type RepetitionDetectionParams = Any

type RequestOutputKind = Any

type SamplingParams = Any

type StructuredOutputsParams = Any

type TokenizeParams = Any

class VLLMValidationError(ValueError): ...

def merge_kwargs(*dicts): ...

def replace(obj, **kw): ...

_INT64_MIN = -2 ** 63
_INT64_MAX = 2 ** 63 - 1

class ChatMessage(OpenAIBaseModel):
    role: str
    content: str | None = None
    refusal: str | None = None
    annotations: OpenAIAnnotation | None = None
    audio: OpenAIChatCompletionAudio | None = None
    function_call: FunctionCall | None = None
    tool_calls: list[ToolCall] = Field(default_factory=list)
    reasoning: str | None = None

class ChatCompletionLogProb(OpenAIBaseModel):
    token: str
    logprob: float = -9999.0
    bytes: list[int] | None = None

class ChatCompletionLogProbsContent(ChatCompletionLogProb):
    field_names: ClassVar[set[str] | None] = None
    top_logprobs: list[ChatCompletionLogProb] = Field(default_factory=list)

class ChatCompletionLogProbs(OpenAIBaseModel):
    content: list[ChatCompletionLogProbsContent] | None = None

class ChatCompletionResponseChoice(OpenAIBaseModel):
    index: int
    message: ChatMessage
    logprobs: ChatCompletionLogProbs | None = None
    finish_reason: str | None = 'stop'
    stop_reason: int | str | None = None
    token_ids: list[int] | None = None

class ChatCompletionResponse(OpenAIBaseModel):
    id: str = Field(default_factory=lambda: f'chatcmpl-{random_uuid()}')
    object: Literal['chat.completion'] = 'chat.completion'
    created: int = Field(default_factory=lambda: int(time.time()))
    model: str
    choices: list[ChatCompletionResponseChoice]
    service_tier: Literal['auto', 'default', 'flex', 'scale', 'priority'] | None = None
    system_fingerprint: str | None = None
    usage: UsageInfo
    prompt_logprobs: list[dict[int, Logprob] | None] | None = None
    prompt_token_ids: list[int] | None = None
    kv_transfer_params: dict[str, Any] | None = Field(default=None, description='KVTransfer parameters.')

class ChatCompletionResponseStreamChoice(OpenAIBaseModel):
    index: int
    delta: DeltaMessage
    logprobs: ChatCompletionLogProbs | None = None
    finish_reason: str | None = None
    stop_reason: int | str | None = None
    token_ids: list[int] | None = None

class ChatCompletionStreamResponse(OpenAIBaseModel):
    id: str = Field(default_factory=lambda: f'chatcmpl-{random_uuid()}')
    object: Literal['chat.completion.chunk'] = 'chat.completion.chunk'
    created: int = Field(default_factory=lambda: int(time.time()))
    model: str
    choices: list[ChatCompletionResponseStreamChoice]
    usage: UsageInfo | None = Field(default=None)
    prompt_token_ids: list[int] | None = None

class ChatCompletionToolsParam(OpenAIBaseModel):
    type: Literal['function'] = 'function'
    function: FunctionDefinition

class ChatCompletionNamedFunction(OpenAIBaseModel):
    name: str

class ChatCompletionNamedToolChoiceParam(OpenAIBaseModel):
    function: ChatCompletionNamedFunction
    type: Literal['function'] = 'function'

class ChatCompletionRequest(OpenAIBaseModel):
    messages: list[ChatCompletionMessageParam]
    model: str | None = None
    frequency_penalty: float | None = 0.0
    logit_bias: dict[str, float] | None = None
    logprobs: bool | None = False
    top_logprobs: int | None = 0
    max_tokens: int | None = Field(default=None, deprecated='max_tokens is deprecated in favor of the max_completion_tokens field')
    max_completion_tokens: int | None = None
    n: int | None = 1
    presence_penalty: float | None = 0.0
    response_format: AnyResponseFormat | None = None
    seed: int | None = Field(None, ge=_INT64_MIN, le=_INT64_MAX)
    stop: str | list[str] | None = []
    stream: bool | None = False
    stream_options: StreamOptions | None = None
    temperature: float | None = None
    top_p: float | None = None
    tools: list[ChatCompletionToolsParam] | None = None
    tool_choice: Literal['none'] | Literal['auto'] | Literal['required'] | ChatCompletionNamedToolChoiceParam | None = 'none'
    reasoning_effort: Literal['none', 'low', 'medium', 'high'] | None = None
    include_reasoning: bool = True
    parallel_tool_calls: bool | None = True
    user: str | None = None
    use_beam_search: bool = False
    top_k: int | None = None
    min_p: float | None = None
    repetition_penalty: float | None = None
    length_penalty: float = 1.0
    stop_token_ids: list[int] | None = []
    include_stop_str_in_output: bool = False
    ignore_eos: bool = False
    min_tokens: int = 0
    skip_special_tokens: bool = True
    spaces_between_special_tokens: bool = True
    truncate_prompt_tokens: Annotated[int, Field(ge=-1, le=_INT64_MAX)] | None = None
    prompt_logprobs: int | None = None
    allowed_token_ids: list[int] | None = None
    bad_words: list[str] = Field(default_factory=list)
    echo: bool = Field(default=False, description='If true, the new message will be prepended with the last message if they belong to the same role.')
    add_generation_prompt: bool = Field(default=True, description='If true, the generation prompt will be added to the chat template. This is a parameter used by chat template in tokenizer config of the model.')
    continue_final_message: bool = Field(default=False, description='If this is set, the chat will be formatted so that the final message in the chat is open-ended, without any EOS tokens. The model will continue this message rather than starting a new one. This allows you to "prefill" part of the model\'s response for it. Cannot be used at the same time as `add_generation_prompt`.')
    add_special_tokens: bool = Field(default=False, description='If true, special tokens (e.g. BOS) will be added to the prompt on top of what is added by the chat template. For most models, the chat template takes care of adding the special tokens so this should be set to false (as is the default).')
    documents: list[dict[str, str]] | None = Field(default=None, description='A list of dicts representing documents that will be accessible to the model if it is performing RAG (retrieval-augmented generation). If the template does not support RAG, this argument will have no effect. We recommend that each document should be a dict containing "title" and "text" keys.')
    chat_template: str | None = Field(default=None, description='A Jinja template to use for this conversion. As of transformers v4.44, default chat template is no longer allowed, so you must provide a chat template if the tokenizer does not define one.')
    chat_template_kwargs: dict[str, Any] | None = Field(default=None, description='Additional keyword args to pass to the template renderer. Will be accessible by the chat template.')
    media_io_kwargs: dict[str, dict[str, Any]] | None = Field(default=None, description='Additional kwargs to pass to the media IO connectors, keyed by modality. Merged with engine-level media_io_kwargs.')
    mm_processor_kwargs: dict[str, Any] | None = Field(default=None, description='Additional kwargs to pass to the HF processor.')
    structured_outputs: StructuredOutputsParams | None = Field(default=None, description='Additional kwargs for structured outputs')
    priority: int = Field(default=0, ge=_INT64_MIN, le=_INT64_MAX, description='The priority of the request (lower means earlier handling; default: 0). Any priority other than 0 will raise an error if the served model does not use priority scheduling.')
    request_id: str = Field(default_factory=random_uuid, description='The request_id related to this request. If the caller does not set it, a random_uuid will be generated. This id is used through out the inference process and return in response.')
    return_tokens_as_token_ids: bool | None = Field(default=None, description="If specified with 'logprobs', tokens are represented  as strings of the form 'token_id:{token_id}' so that tokens that are not JSON-encodable can be identified.")
    return_token_ids: bool | None = Field(default=None, description='If specified, the result will include token IDs alongside the generated text. In streaming mode, prompt_token_ids is included only in the first chunk, and token_ids contains the delta tokens for each chunk. This is useful for debugging or when you need to map generated text back to input tokens.')
    cache_salt: str | None = Field(default=None, description='If specified, the prefix cache will be salted with the provided string to prevent an attacker to guess prompts in multi-user environments. The salt should be random, protected from access by 3rd parties, and long enough to be unpredictable (e.g., 43 characters base64-encoded, corresponding to 256 bit).')
    kv_transfer_params: dict[str, Any] | None = Field(default=None, description='KVTransfer parameters used for disaggregated serving.')
    vllm_xargs: dict[str, str | int | float | list[str | int | float]] | None = Field(default=None, description='Additional request parameters with (list of) string or numeric values, used by custom extensions.')
    repetition_detection: RepetitionDetectionParams | None = Field(default=None, description="Parameters for detecting repetitive N-gram patterns in output tokens. If such repetition is detected, generation will be ended early. LLMs can sometimes generate repetitive, unhelpful token patterns, stopping only when they hit the maximum output length (e.g. 'abcdabcdabcd...' or '\\emoji \\emoji \\emoji ...'). This feature can detect such behavior and terminate early, saving time and tokens.")
    _DEFAULT_SAMPLING_PARAMS: dict = {'repetition_penalty': 1.0, 'temperature': 1.0, 'top_p': 1.0, 'top_k': 0, 'min_p': 0.0}
