# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
# AUTO-GENERATED by types_gen.py — do not edit manually

import time
from typing import Any, Literal, TypeAlias
from openai.types.responses import ResponseCodeInterpreterCallCodeDeltaEvent, ResponseCodeInterpreterCallCodeDoneEvent, ResponseCodeInterpreterCallCompletedEvent, ResponseCodeInterpreterCallInProgressEvent, ResponseCodeInterpreterCallInterpretingEvent, ResponseContentPartAddedEvent, ResponseContentPartDoneEvent, ResponseInputItemParam, ResponseMcpCallArgumentsDeltaEvent, ResponseMcpCallArgumentsDoneEvent, ResponseMcpCallCompletedEvent, ResponseMcpCallInProgressEvent, ResponseOutputItem, ResponseOutputItemAddedEvent, ResponseOutputItemDoneEvent, ResponsePrompt, ResponseReasoningTextDeltaEvent, ResponseReasoningTextDoneEvent, ResponseStatus, ResponseTextConfig, ResponseWebSearchCallCompletedEvent, ResponseWebSearchCallInProgressEvent, ResponseWebSearchCallSearchingEvent
from openai.types.responses import ResponseCompletedEvent as OpenAIResponseCompletedEvent
from openai.types.responses import ResponseCreatedEvent as OpenAIResponseCreatedEvent
from openai.types.responses import ResponseInProgressEvent as OpenAIResponseInProgressEvent
from openai.types.responses.response import IncompleteDetails, ToolChoice
from openai.types.responses.response_reasoning_item import Content as ResponseReasoningTextContent
from openai.types.responses.tool import Tool
from openai.types.shared import Metadata, Reasoning
from openai_harmony import Message as OpenAIHarmonyMessage
from pydantic import Field
from llm_gateway.types.chat_utils import ChatCompletionMessageParam
from llm_gateway.types.openai.engine.protocol import OpenAIBaseModel
from llm_gateway.types.utils import random_uuid

type ChatParams = Any

type ModelConfig = Any

type RequestOutputKind = Any

type SamplingParams = Any

type StructuredOutputsParams = Any

type TokenizeParams = Any

class VLLMValidationError(ValueError): ...

def merge_kwargs(*dicts): ...

_INT64_MIN = -2 ** 63
_INT64_MAX = 2 ** 63 - 1

class InputTokensDetails(OpenAIBaseModel):
    cached_tokens: int
    input_tokens_per_turn: list[int] = Field(default_factory=list)
    cached_tokens_per_turn: list[int] = Field(default_factory=list)

class OutputTokensDetails(OpenAIBaseModel):
    reasoning_tokens: int = 0
    tool_output_tokens: int = 0
    output_tokens_per_turn: list[int] = Field(default_factory=list)
    tool_output_tokens_per_turn: list[int] = Field(default_factory=list)

class ResponseUsage(OpenAIBaseModel):
    input_tokens: int
    input_tokens_details: InputTokensDetails
    output_tokens: int
    output_tokens_details: OutputTokensDetails
    total_tokens: int

def serialize_message(msg):
    """
    Serializes a single message
    """
    if isinstance(msg, dict):
        return msg
    elif hasattr(msg, 'to_dict'):
        return msg.to_dict()
    else:
        return msg.model_dump_json()

def serialize_messages(msgs):
    """
    Serializes multiple messages
    """
    return [serialize_message(msg) for msg in msgs] if msgs else None

class ResponseRawMessageAndToken(OpenAIBaseModel):
    """Class to show the raw message.
    If message / tokens diverge, tokens is the source of truth"""
    message: str
    tokens: list[int]
    type: Literal['raw_message_tokens'] = 'raw_message_tokens'
ResponseInputOutputMessage: TypeAlias = list[ChatCompletionMessageParam] | list[ResponseRawMessageAndToken]
ResponseInputOutputItem: TypeAlias = ResponseInputItemParam | ResponseOutputItem

class ResponsesRequest(OpenAIBaseModel):
    background: bool | None = False
    include: list[Literal['code_interpreter_call.outputs', 'computer_call_output.output.image_url', 'file_search_call.results', 'message.input_image.image_url', 'message.output_text.logprobs', 'reasoning.encrypted_content'],] | None = None
    input: str | list[ResponseInputOutputItem]
    instructions: str | None = None
    max_output_tokens: int | None = None
    max_tool_calls: int | None = None
    metadata: Metadata | None = None
    model: str | None = None
    logit_bias: dict[str, float] | None = None
    parallel_tool_calls: bool | None = True
    previous_response_id: str | None = None
    prompt: ResponsePrompt | None = None
    reasoning: Reasoning | None = None
    service_tier: Literal['auto', 'default', 'flex', 'scale', 'priority'] = 'auto'
    store: bool | None = True
    stream: bool | None = False
    temperature: float | None = None
    text: ResponseTextConfig | None = None
    tool_choice: ToolChoice = 'auto'
    tools: list[Tool] = Field(default_factory=list)
    top_logprobs: int | None = 0
    top_p: float | None = None
    top_k: int | None = None
    truncation: Literal['auto', 'disabled'] | None = 'disabled'
    user: str | None = None
    skip_special_tokens: bool = True
    include_stop_str_in_output: bool = False
    prompt_cache_key: str | None = Field(default=None, description='A key that was used to read from or write to the prompt cache.Note: This field has not been implemented yet and vLLM will ignore it.')
    request_id: str = Field(default_factory=lambda: f'resp_{random_uuid()}', description='The request_id related to this request. If the caller does not set it, a random_uuid will be generated. This id is used through out the inference process and return in response.')
    media_io_kwargs: dict[str, dict[str, Any]] | None = Field(default=None, description='Additional kwargs to pass to the media IO connectors, keyed by modality. Merged with engine-level media_io_kwargs.')
    mm_processor_kwargs: dict[str, Any] | None = Field(default=None, description='Additional kwargs to pass to the HF processor.')
    priority: int = Field(default=0, ge=_INT64_MIN, le=_INT64_MAX, description='The priority of the request (lower means earlier handling; default: 0). Any priority other than 0 will raise an error if the served model does not use priority scheduling.')
    cache_salt: str | None = Field(default=None, description='If specified, the prefix cache will be salted with the provided string to prevent an attacker to guess prompts in multi-user environments. The salt should be random, protected from access by 3rd parties, and long enough to be unpredictable (e.g., 43 characters base64-encoded, corresponding to 256 bit).')
    enable_response_messages: bool = Field(default=False, description='Dictates whether or not to return messages as part of the response object. Currently only supported for non-background.')
    previous_input_messages: list[OpenAIHarmonyMessage | dict] | None = None
    structured_outputs: StructuredOutputsParams | None = Field(default=None, description='Additional kwargs for structured outputs')
    repetition_penalty: float | None = None
    seed: int | None = Field(None, ge=_INT64_MIN, le=_INT64_MAX)
    stop: str | list[str] | None = []
    ignore_eos: bool = False
    vllm_xargs: dict[str, str | int | float | list[str | int | float]] | None = Field(default=None, description='Additional request parameters with (list of) string or numeric values, used by custom extensions.')
    _DEFAULT_SAMPLING_PARAMS = {'temperature': 1.0, 'top_p': 1.0, 'top_k': 0}

class ResponsesResponse(OpenAIBaseModel):
    id: str = Field(default_factory=lambda: f'resp_{random_uuid()}')
    created_at: int = Field(default_factory=lambda: int(time.time()))
    incomplete_details: IncompleteDetails | None = None
    instructions: str | None = None
    metadata: Metadata | None = None
    model: str
    object: Literal['response'] = 'response'
    output: list[ResponseOutputItem]
    parallel_tool_calls: bool
    temperature: float
    tool_choice: ToolChoice
    tools: list[Tool]
    top_p: float
    background: bool
    max_output_tokens: int
    max_tool_calls: int | None = None
    previous_response_id: str | None = None
    prompt: ResponsePrompt | None = None
    reasoning: Reasoning | None = None
    service_tier: Literal['auto', 'default', 'flex', 'scale', 'priority']
    status: ResponseStatus
    text: ResponseTextConfig | None = None
    top_logprobs: int | None = None
    truncation: Literal['auto', 'disabled']
    usage: ResponseUsage | None = None
    user: str | None = None
    input_messages: ResponseInputOutputMessage | None = Field(default=None, description='If enable_response_messages, we can show raw token input to model.')
    output_messages: ResponseInputOutputMessage | None = Field(default=None, description='If enable_response_messages, we can show raw token output of model.')

class ResponseReasoningPartDoneEvent(OpenAIBaseModel):
    content_index: int
    'The index of the content part that is done.'
    item_id: str
    'The ID of the output item that the content part was added to.'
    output_index: int
    'The index of the output item that the content part was added to.'
    part: ResponseReasoningTextContent
    'The content part that is done.'
    sequence_number: int
    'The sequence number of this event.'
    type: Literal['response.reasoning_part.done']
    'The type of the event. Always `response.reasoning_part.done`.'

class ResponseReasoningPartAddedEvent(OpenAIBaseModel):
    content_index: int
    'The index of the content part that is done.'
    item_id: str
    'The ID of the output item that the content part was added to.'
    output_index: int
    'The index of the output item that the content part was added to.'
    part: ResponseReasoningTextContent
    'The content part that is done.'
    sequence_number: int
    'The sequence number of this event.'
    type: Literal['response.reasoning_part.added']
    'The type of the event. Always `response.reasoning_part.added`.'

class ResponseCompletedEvent(OpenAIResponseCompletedEvent):
    response: ResponsesResponse

class ResponseCreatedEvent(OpenAIResponseCreatedEvent):
    response: ResponsesResponse

class ResponseInProgressEvent(OpenAIResponseInProgressEvent):
    response: ResponsesResponse
StreamingResponsesResponse: TypeAlias = ResponseCreatedEvent | ResponseInProgressEvent | ResponseCompletedEvent | ResponseOutputItemAddedEvent | ResponseOutputItemDoneEvent | ResponseContentPartAddedEvent | ResponseContentPartDoneEvent | ResponseReasoningTextDeltaEvent | ResponseReasoningTextDoneEvent | ResponseReasoningPartAddedEvent | ResponseReasoningPartDoneEvent | ResponseCodeInterpreterCallInProgressEvent | ResponseCodeInterpreterCallCodeDeltaEvent | ResponseWebSearchCallInProgressEvent | ResponseWebSearchCallSearchingEvent | ResponseWebSearchCallCompletedEvent | ResponseCodeInterpreterCallCodeDoneEvent | ResponseCodeInterpreterCallInterpretingEvent | ResponseCodeInterpreterCallCompletedEvent | ResponseMcpCallArgumentsDeltaEvent | ResponseMcpCallArgumentsDoneEvent | ResponseMcpCallInProgressEvent | ResponseMcpCallCompletedEvent
